name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos-14:
    name: Build macOS 14 (Swift 5.10)
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: swift build -v
  macos-15:
    name: Build macOS 15 (Swift 6.0)
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  ios-15:
    name: Build on iOS 15
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode 16.2
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Restore Cached iOS Simulator Runtime
      uses: actions/cache@v4
      id: cache-ios-15-runtime
      with:
        path: /Library/Developer/CoreSimulator/Profiles/Runtimes
        key: ios-runtime-15.5
    - name: Set up iOS 15 simulator runtime (if not cached)
      if: steps.cache-ios-15-runtime.outputs.cache-hit != 'true'
      run: sudo xcodes runtimes install "iOS 15.5"
    - name: Create iOS 15 simulator
      run: xcrun simctl create "iPhone 13 Pro" "iPhone 13 Pro" "com.apple.CoreSimulator.SimRuntime.iOS-15-5"
    - name: Build
      run: xcodebuild build -scheme EventSource -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.5'
    - name: Run tests
      run: xcodebuild test -scheme EventSource -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.5'
  ubuntu:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
