name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos-14:
    name: Build macOS 14 (Swift 5.10)
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: swift build -v
  macos-15:
    name: Build macOS 15 (Swift 6.0)
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  ios-15:
    name: Build on iOS 15
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Runtimes Directory
      run: mkdir -p $HOME/Runtimes
    - name: Restore cached iOS simulator runtime
      id: cache-restore
      uses: actions/cache@v4
      with:
        path: $HOME/Runtimes
        key: ios-runtime-15.5-${{ runner.os }}-${{ hashFiles('**/ci.yml') }}
        restore-keys: |
          ios-runtime-15.5-${{ runner.os }}-
          ios-runtime-15.5-
    - name: Set up iOS 15 simulator runtime
      run: sudo xcodes runtimes install "iOS 15.5" --directory $HOME/Runtimes --keep-archive
    - name: Build
      run: xcodebuild build -scheme EventSource -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.5'
    - name: Run tests
      run: xcodebuild test -scheme EventSource -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.5'
  ubuntu:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
